### ISSUE TITLE
Running issue on single processor

### ISSUE THREAD

**Issue by subhk** [aharwood2/LUMA#10]
white executing below errors showing up  - 
Running LUMA -- Version 1.7.4
(Serial Build)
*** The MPI_Cart_create() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[jupiter:7684] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!

**Comment by aharwood2** [comment]
Could you attach your definitions file, geometry config file and any point clouds so we can recreate your issue?

Also, you may wish to update to the latest version (currently 1.7.8) to see if the issue disappears.

**Comment by subhk** [comment]
Thanks, Adrian. I have attached the definition file and geometry file. I am
not using point clouds.

I will try with the latest version.

Thanks for your help.

Subhajit

**Comment by subhk** [comment]
I checked with 1.7.8. Same errors appear.

**Comment by aharwood2** [comment]
Ok thanks, I can't see your attachments -- can you check you attached them properly?

**Comment by subhk** [comment]
here I have shared the zip file contain definition.h and geometry.config 
[files.zip](https://github.com/aharwood2/LUMA/files/3901199/files.zip)

**Comment by aharwood2** [comment]
Hi Subhajit, I've patched this now and it tests OK on our systems. If you pull the head of the master you can test v1.7.9. Thanks for reporting the issue.

**Comment by subhk** [comment]
Thank you very much, Adrian. It is running now.

Thanks,
Subhajit Kar
