### ISSUE TITLE
MPI issue

### ISSUE THREAD

**Issue by zliu72** [aharwood2/LUMA#13]
I am trying to benchmark the LUMA with 3D sphere flow case, similiar to those in JAS Munoz's thesis. The code always get error bellow when the grids exceed 20 million nodes. 

Is that means the memory or MPI exceeds the limits? If it is, what is the limit for current code? It seems the grid system is not distributed storaged. 

Best,

Zhaohui
-------------------------------------------------
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Fatal error in PMPI_Barrier: Unknown error class, error stack:
PMPI_Barrier(425).....................: MPI_Barrier(comm=0x84000004) failed
MPIR_Barrier_impl(332)................: Failure during collective
MPIR_Barrier_impl(327)................:
MPIR_Barrier(292).....................:
MPIR_Barrier_intra(150)...............:
barrier_smp_intra(96).................:

**Comment by ianhinder** [comment]
This looks like you don't have enough memory for the size of grid you are asking for.  It shouldn't be related to MPI.  How many MPI processes are you using, and have you tried running on more?

**Comment by zliu72** [comment]
Thanks ianhinder，
As you suggested, I had tried using different MPI configuration, such as 4*2*2, 4*3*3 and 4*4*4. It seems the problem is related to the RKPM method adopted in LUMA. 
Another problem arises, however. If the resolution for statinary 3D sphere is high, the matrix solved by LAPACK to get epsilon could exceed 50000*50000, which become untolerable for memory and computing time. To avoid that, you could try Boundary Thickening concept （J. Comp. Physics 390(2019)203–231).
Best，
Zhaohui

**Comment by ianhinder** [comment]
I'm not really following.  Can you attach your definitions.h file to this issue (drag the file into the comment box) and tell us the mpirun command you are using?  Also, are you running this on a cluster or a workstation?

**Comment by aharwood2** [comment]
@zliu72, are you still having issues? I will close the issue if we haven't heard back by the end of the month.
