### ISSUE TITLE
Error in making LUMA

### ISSUE THREAD

**Issue by Akarshr1234** [aharwood2/LUMA#15]
Hi,
I am trying to install LUMA in my Ubuntu 20.04 system. I had built all the dependencies.
When I start making by `make` command in LUMA directory everything works fine until it start using lapack libraries.
I am attaching a text file containing error I get.
[input_output.txt](https://github.com/cfdemons/LUMA/files/6572093/input_output.txt)
One more thing I like to add, the error seems to be same when I try to compile a cpp file using lapack blas libraries without using gfortran and blas, i.e., if I use `g++ -o test test.cpp -llapack` instead of `g++ -o  test test.cpp -llapack -lblas -lgfortran`

Hope you may help.
Thank you.

**Comment by ianhinder** [comment]
Please could you try adding `-lblas` to the line
```
LIB=-L$(HDF5_HOME)/lib -lhdf5 -llapack
```
in the makefile, so that it looks like
```
LIB=-L$(HDF5_HOME)/lib -lhdf5 -llapack -lblas
```
and report back?

**Comment by Akarshr1234** [comment]
Hi,
I added  -lblas in make file. Now the u defined reference to dgetrs.f and dgetrf2.f  functions are gone but I am still getting undefined reference to xerbla.f. I am attaching the text file of the error I am getting now.
[input_output_2.txt](https://github.com/cfdemons/LUMA/files/6575693/input_output_2.txt)

Thank you.

**Comment by ianhinder** [comment]
Please can you add `-lgfortran` as well?

**Comment by Akarshr1234** [comment]
Yes, it works.
Thank you for helping me.

**Comment by ianhinder** [comment]
I just googled the error messages 🙂  I don't know why the default makefile isn't working for you - perhaps something has changed with LAPACK in the newer versions of Ubuntu.  I assume you just followed the instruction for the dependencies?  We should test them with current Ubuntu and fix them. Thanks for finding the problem!

**Comment by Akarshr1234** [comment]
Yes, I had followed the instructions for the dependencies but for VTK and LAPACK the instructions are missing. It would be great if those are present there for LINUX/MAC. 
By the way it was nice to talk to you.
