### ISSUE TITLE
Issue while making h5mgm merge tool

### ISSUE THREAD

**Issue by paulakash24** [aharwood2/LUMA#16]
Hello,

I am trying to configure the merge tool `h5mgm`. I changed the version of the `VTK` in the makefile with the version present in my system.

But while making I am getting an error msg:

```
g++    -c -o src/h5mgm.o src/h5mgm.cpp
In file included from src/VelocitySorter.h:16,
                 from src/h5mgm.cpp:16:
src/h5mgm.h:20:10: fatal error: hdf5.h: No such file or directory
   20 | #include "hdf5.h"
      |          ^~~~~~~~
compilation terminated.
make: *** [<builtin>: src/h5mgm.o] Error 1
```
While making the file in the LUMA source directory, it is working without errors. I believe the h5mgm makefile also uses the same definition HDF5_HOME definition that the LUMA makefile does. Correct me if I am wrong.

Any help would be highly appreciated

**Comment by paulakash24** [comment]
Hi, 
If I have missed any info, let me share those now:

-> I am using LUMA 1.7.11, and running on Ubuntu 20.04.
-> I have built and also installed VTK 8.2.0 before trying to make the merge tool.

Thanks
Akash

**Comment by ianhinder** [comment]
We think we know what's wrong, and have fixes already - we're just working on the best way to release them.  Hopefully we'll get this done in the next couple of days.

**Comment by paulakash24** [comment]
Thank you.

Looking forward to the release.

**Comment by ianhinder** [comment]
I've just pushed 1.7.12.  Please can you try updating with
```
git pull
```
and making the merge tool again?

**Comment by paulakash24** [comment]
Hi,

Your fix `(regarding the hdf5.h)` has worked. There were some issues on my end which are sorted and now the merge tool has been made.

Thnak You for the support. I think that it would be fine to close the issue.

**Comment by ianhinder** [comment]
Happy to help!
