### ISSUE TITLE
Importing flexible geometry from pointcloud

### ISSUE THREAD

**Issue by Chait263** [aharwood2/LUMA#18]
Hello hope all of you are doing well. 
We are trying to import an airfoil for our 2-D simulations. We kept the chord length as more than 20 times the thickness of the foil and mentioned it to be flexible. We got an error while we do this. However when we specify it to be rigid there is no error.  
This is how we are calling the pointcloud-
FROM_FILE IBM pointcloud_NACA0004_2D.in 0 0 START 0.5 START 0.98 CENTRE 0.0 1 X FLEXIBLE CLAMPED
Our  domain size is 4 x 2.

For our purpose we want to be able to specify the foil to be flexible and mention the Young's Modulus if possible. Is there any condition that is used to categorize if a pointcloud object can be specified flexible or not? 

Another issue is that even after specifying the airfoil geometry in the pointcloud once it is actually imported to LUMA, the IB markers do not converge on the trailing edge. Below I have attached images of this, second image is the zoomed in view.

![airfoil](https://user-images.githubusercontent.com/68155618/125190605-a0a4fa80-e25b-11eb-9b1e-5fd2a0a38146.jpeg)
![airfoil_zoomed](https://user-images.githubusercontent.com/68155618/125190609-a39feb00-e25b-11eb-9c15-2b202c4d3dbf.jpeg)

**Comment by martacamps** [comment]
Hello, 

Flexible bodies imported from point clouds are not supported in LUMA. For LUMA to work with flexible bodies from point cloud, the LUMA structural solver needs to use the point cloud geometry as input and this is not supported by the current LUMA structural solver. 

About the second issue, LUMA reads in the point cloud object and assigns one IBM marker for each cell that contains one or more points of the point cloud object. Because the point cloud has no connectivity information, LUMA is unable to detect if the object should be closed and thus there is a gap.

**Comment by Chait263** [comment]
Thanks for taking time out to help us. 

We are a little bit worried that the open trailing edge may give us some bad results if the flow enters through those open areas since our motion will be oscillating making the airfoil flap.

In the pointcloud file, we mentioned the start-point and end-point to be the same (with the same coordinates). Can't we do something so that LUMA uses this format to understand that it needs to close the edge?

**Comment by Chait263** [comment]
Hello, 

We made some changes in the file body.h to try and close out the open body we got after importing from pointcloud. 

```
template <typename MarkerType>
Body<MarkerType>::Body(GridObj* g, int bodyID, PCpts* _PCpts)
	: _Owner(g), id(bodyID)
{
	// Set as unclosed surface by default
	this->closed_surface = false;

	// Set level
	this->level = _Owner->level;

	// Set the rank which owns this body
	this->owningRank = assignOwningRank(id);

	// Call method to build from point cloud
	this->buildFromCloud(_PCpts);
};
```


We changed to `this->closed_surface = true;` and were able to close out the body. 
The shape we get after this is attached below

![WhatsApp Image 2021-07-30 at 5 59 59 PM](https://user-images.githubusercontent.com/68155618/127657875-a5325709-edf8-4799-aad9-5bb2446269af.jpeg)

![WhatsApp Image 2021-07-30 at 5 59 59 PM (1)](https://user-images.githubusercontent.com/68155618/127657138-9b6daeee-b506-45f6-8161-8d17ec48e075.jpeg)

There still seems to be some irregularity at the trailing edge of the foil.
Is there any way to correct this irregularity? Also what are the effects of changing this statement if any? 

Thank You for taking time to help us.

**Comment by martacamps** [comment]
Hello, 

The `closed_surface` attribute only influences the way the point cloud object is written into the .vtk output file. If `closed_surface == true`, the `vtk_out.BodyX.Y.t.vtk` file contains an extra line that joins the last marker coordinate with the first one. This change doesn't affect the solver in any other way. 

Looking at the figure from your first post, I would expect that `closed_surface = true` would have joined the last point with the first point, thus closing the gap. The picture in your latest post seems to have an extra marker with the same y coordinate as the last point and an a different x coordinate. I could be helpful to check the difference between the  coordinates in `vtk_out.BodyX.Y.t.vtk` and the coordinates in the original point cloud file and how they fit with the coordinates of the LUMA cells.

**Comment by paulakash24** [comment]
Yes. In the `vtk_out.Body.X.Y.t.vtk` file there are some points which have same y coordinate for different x values. However, our `pointcloud` file is fine. The `pointcloud` file has 220 points.

We are sharing the `pointcloud` file named `Teardrop_0.167.in `and the `vtk_out.Body.0.0.0.vtk` files as you have suggested. Please have a look.

I have linked the files in google drive as the extension were not supported here. Here is the link:
https://drive.google.com/drive/folders/1wMNxK0KiGCnKiMzffdo_ttKyIAcEZqyS?usp=sharing

**Comment by martacamps** [comment]
The first 4 points of the .vtk file have the same y coordinate. The .vtk file also has 181 points, while the .pc file has 220 points. Probably, the LBM mesh is not fine enough to accurately represent the coordinates in the .pc file at the tail of the airfoil.

![image](https://user-images.githubusercontent.com/15945173/128534069-3f2dc36a-a821-42d8-8edc-21801a15d181.png)
