### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by huadongy** [aharwood2/LUMA#7]
Error building LUMA on gcc 4.4.7

mpicxx -O3 -std=c++0x -w -fopenmp -I/chalmers/sw/sup64/hdf5-1.10.3//include -c -o obj/BFLBody.o src/BFLBody.cpp
In file included from src/../inc/MpiManager.h:27,
                 from src/../inc/stdafx.h:206,
                 from src/BFLBody.cpp:23:
src/../inc/HDFstruct.h:45: error: ISO C++ forbids initialization of member ‘writable_data_count’
src/../inc/HDFstruct.h:45: error: making ‘writable_data_count’ static
src/../inc/HDFstruct.h:45: error: ISO C++ forbids in-class initialization of non-const static member ‘writable_data_count’
In file included from src/../inc/GridUtils.h:27,
                 from src/../inc/stdafx.h:207,
                 from src/BFLBody.cpp:23:
src/../inc/GridObj.h:58: error: ‘nullptr’ was not declared in this scope
src/../inc/GridObj.h:58: error: ISO C++ forbids initialization of member ‘parentGrid’
src/../inc/GridObj.h:58: error: making ‘parentGrid’ static
src/../inc/GridObj.h:58: error: invalid in-class initialization of static data member of non-integral type ‘GridObj*’
In file included from src/../inc/stdafx.h:207,
                 from src/BFLBody.cpp:23:
src/../inc/GridUtils.h:95: error: ‘nullptr’ was not declared in this scope
src/../inc/GridUtils.h:95: error: ‘nullptr’ was not declared in this scope
src/../inc/GridUtils.h:96: error: ‘nullptr’ was not declared in this scope
src/../inc/GridUtils.h:98: error: ‘nullptr’ was not declared in this scope
src/../inc/GridUtils.h:98: error: ‘nullptr’ was not declared in this scope
src/../inc/GridUtils.h:98: error: ‘nullptr’ was not declared in this scope
src/../inc/GridUtils.h:116: error: ‘nullptr’ was not declared in this scope
In file included from src/../inc/BFLBody.h:27,
                 from src/BFLBody.cpp:24:
src/../inc/Body.h: In constructor ‘Body<MarkerType>::Body()’:
src/../inc/Body.h:102: error: ‘nullptr’ was not declared in this scope
src/../inc/Body.h: In member function ‘MarkerData* Body<MarkerType>::getMarkerData(double, double, double)’:
src/../inc/Body.h:584: error: ‘nullptr’ was not declared in this scope
src/../inc/Body.h: In member function ‘virtual void Body<MarkerType>::writeVtkPosition(int)’:
src/../inc/Body.h:800: error: call of overloaded ‘to_string(int&)’ is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
src/../inc/Body.h:807: error: call of overloaded ‘to_string(int&)’ is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
src/../inc/Body.h:813: error: expected initializer before ‘:’ token
src/../inc/Body.h:821: error: expected primary-expression before ‘nLines’
src/../inc/Body.h:821: error: expected ‘;’ before ‘nLines’
src/../inc/Body.h:821: error: ‘nLines’ was not declared in this scope
src/../inc/Body.h:821: error: expected ‘)’ before ‘;’ token
src/../inc/Body.h:823: error: ‘nLines’ was not declared in this scope
src/../inc/Body.h:825: error: ‘nLines’ was not declared in this scope
src/../inc/Body.h:828: error: ‘nLines’ was not declared in this scope
In file included from src/../inc/BFLBody.h:28,
                 from src/BFLBody.cpp:24:
src/../inc/BFLMarker.h: At global scope:
src/../inc/BFLMarker.h:53: error: ISO C++ forbids initialization of member ‘forceX’
src/../inc/BFLMarker.h:53: error: making ‘forceX’ static
src/../inc/BFLMarker.h:53: error: ISO C++ forbids in-class initialization of non-const static member ‘forceX’
src/../inc/BFLMarker.h:54: error: ISO C++ forbids initialization of member ‘forceY’
src/../inc/BFLMarker.h:54: error: making ‘forceY’ static
src/../inc/BFLMarker.h:54: error: ISO C++ forbids in-class initialization of non-const static member ‘forceY’
src/../inc/BFLMarker.h:55: error: ISO C++ forbids initialization of member ‘forceZ’
src/../inc/BFLMarker.h:55: error: making ‘forceZ’ static
src/../inc/BFLMarker.h:55: error: ISO C++ forbids in-class initialization of non-const static member ‘forceZ’
src/BFLBody.cpp: In member function ‘void BFLBody::initialise()’:
src/BFLBody.cpp:73: error: expected initializer before ‘:’ token
src/BFLBody.cpp:81: error: expected ‘)’ before ‘;’ token
src/BFLBody.cpp: In constructor ‘BFLBody::BFLBody(GridObj*, int, PCpts*)’:
src/BFLBody.cpp:151: error: class ‘BFLBody’ does not have any field named ‘Body’
src/BFLBody.cpp: In constructor ‘BFLBody::BFLBody(GridObj*, int, std::vector<double, std::allocator<double> >&, double, std::vector<double, std::allocator<double> >&)’:
src/BFLBody.cpp:166: error: class ‘BFLBody’ does not have any field named ‘Body’
src/BFLBody.cpp: In constructor ‘BFLBody::BFLBody(GridObj*, int, std::vector<double, std::allocator<double> >&, double)’:
src/BFLBody.cpp:180: error: class ‘BFLBody’ does not have any field named ‘Body’
src/BFLBody.cpp: In constructor ‘BFLBody::BFLBody(GridObj*, int, std::vector<double, std::allocator<double> >&, std::vector<double, std::allocator<double> >&, std::vector<double, std::allocator<double> >&)’:
src/BFLBody.cpp:195: error: class ‘BFLBody’ does not have any field named ‘Body’
src/BFLBody.cpp: In constructor ‘BFLBody::BFLBody(GridObj*, int, std::vector<double, std::allocator<double> >&, double, double, std::vector<double, std::allocator<double> >&)’:
src/BFLBody.cpp:211: error: class ‘BFLBody’ does not have any field named ‘Body’
src/BFLBody.cpp: In member function ‘void BFLBody::computeQ(int, int, int, GridObj*)’:
src/BFLBody.cpp:314: error: expected initializer before ‘:’ token
src/BFLBody.cpp:715: error: expected primary-expression at end of input
src/BFLBody.cpp:715: error: expected ‘;’ at end of input
src/BFLBody.cpp:715: error: expected primary-expression at end of input
src/BFLBody.cpp:715: error: expected ‘)’ at end of input
src/BFLBody.cpp:715: error: expected statement at end of input
src/BFLBody.cpp:715: error: expected ‘}’ at end of input
make: *** [obj/BFLBody.o] Error 1

**Comment by huadongy** [comment]
Issue disappears when built with a later version of GCC. Using 4.8.5 now and it is fine.

**Comment by barracuda156** [comment]
`nullptr` is C++11.
