### ISSUE TITLE
makefile Issues

### ISSUE THREAD

**Issue by huadongy** [aharwood2/LUMA#8]
There are several issues encountered during the build which if addressed would make things more convenient:

1. The LUMA makefile is in a sub-directory but the makefile contents expect it to be in the root directory.    
2. The h5mgm makefile does not use the HDF5_HOME definition that the LUMA makefile does, the path is hard coded.    
3. The path is also hardcoded for VTK when a variable could be used.

**Comment by aharwood2** [comment]
I have a made some reorganisation of the source files. This will be tested to make sure the paths still resolve correctly and pushed as part of the next release.
