### ISSUE TITLE
Issue with using IBM bodies on multiple cores

### ISSUE THREAD

**Issue by aharwood2** [aharwood2/LUMA#9]
Assert errors are produced on 1.7.7 when running the test case on the wiki. This is under investigation.

**Comment by aharwood2** [comment]
A couple of problems have been identified with how IBM bodies are setup on multiple cores and fixed. However, there is still an issue with LAPACK which is not actually part of LUMA. A temporary workaround is being implemented at present and tested. If it works then it will form part of a hotfix for the present version until a longer-term solution can be implemented.

**Comment by aharwood2** [comment]
Further testing seems to suggest the issue is on Windows and the error is not reproduced on our Linux system.

**Comment by aharwood2** [comment]
Testing with the FSI validation case on the Wiki is underway to check the bug has been fixed.

**Comment by aharwood2** [comment]
Cannot reproduce the issue on our Unix system so marking this issue as wontfix.

**Comment by Akarshr1234** [comment]
Hi,
I have to assign some motion in y to a flexible filament, and the
filament's x position has to be determined dynamically. Everything works
fine, but as filament enters another processor, the simulation hangs up
and doesn't proceed further.
I had made a new [issue#19](https://github.com/cfdemons/LUMA/issues/19). Please see it for more details.

Thank you.
